### ISSUE TITLE
The spherical coordinate is not the standard one!

### ISSUE THREAD

**Issue by GiggleLiu** [cormullion/Thebes.jl#15]
This is the definition in the code:
https://github.com/cormullion/Thebes.jl/blob/d976bde778c874a7b6b6dbaada83955aae4f2292/src/Point3D.jl#L172-L176

This is the wiki definition:
https://en.wikipedia.org/wiki/Spherical_coordinate_system

The theta an phi are exchanged, this is so wield.

**Comment by cormullion** [comment]
haha - yes it’s very confusing - I was also confused 😂

<img width="802" alt="Screenshot 2023-10-28 at 14 03 36" src="https://github.com/cormullion/Thebes.jl/assets/52289/9d7ce93f-1f46-4728-a010-27f6b10636de">

(wikipedia)

**Comment by GiggleLiu** [comment]
Oops...
